version: '3'
services:
  tests:
    container_name: laravel-idempotency-middleware-tests
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/code
    working_dir: /code